EIGEN_PATH = '/usr/include/eigen3';
SRC = '../../gpismap/src';
INC = '../../gpismap/include';

disp('Running >> mex mexGPisMap.cpp covFnc.cpp ObsGP.cpp OnGPIS.cpp strct.cpp octree.cpp GPisMap3.cpp...');
mex('mexGPisMap3.cpp',...
    strcat(SRC,'/covFnc.cpp'),...
    strcat(SRC,'/ObsGP.cpp'),...
    strcat(SRC,'/OnGPIS.cpp'),...
    strcat(SRC,'/strct.cpp'),...
    strcat(SRC,'/octree.cpp'),...
    strcat(SRC,'/GPisMap3.cpp'),...
    strcat('-I', INC),...
    strcat('-I', EIGEN_PATH),...
    'CXXFLAGS=-std=c++14 -pthread -fPIC','-O');
